# DA3-{Large / Base / Small} training on 4x4090 GPUs
defaults:
  - model: zipsplat
  - data: composed_252
  - train: zipsplat
  - benchmarks: re10k_dl3dv
  - _self_

# save memory such that models fit in 24GB VRAM (BS=24 per GPU)
model: 
  use_checkpoint: true
  backbone:
    use_checkpoint: true

data:
  batch_size: 96
  image_num_range: [2, 24]
  view_schedule: 0.5
  num_target_views: 4
  preprocessing:
    resize: 252
    edge_divisible_by: 14

train:
  seed: 1
  num_steps: 450_000
  lr: 3e-4
